-- Yard Tracker schema for PostgreSQL. Matches the JPA entities; Hibernate runs with ddl-auto=validate.
-- Only used with the prod profile (spring.flyway.enabled=true). Dev and tests use H2 with ddl-auto.

create table hulls (
    id    bigint generated by default as identity primary key,
    code  varchar(255) not null unique,
    name  varchar(255) not null,
    color varchar(255) not null
);

create table zones (
    id     bigint generated by default as identity primary key,
    code   varchar(255) not null unique,
    name   varchar(255) not null,
    kind   varchar(255),
    points varchar(2000) not null
);

create table items (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null unique,
    type       varchar(255) not null check (type in ('SUB_ASSEMBLY','SECTION','BLOCK','GRAND_BLOCK','UNIT','PIPE_OUTFITTING','TOOL')),
    status     varchar(255) not null check (status in ('ACTIVE','CONSUMED')),
    hull_id    bigint references hulls (id),
    zone_id    bigint references zones (id),
    parent_id  bigint references items (id),
    tag        varchar(255),
    quantity   integer,
    unit       varchar(255),
    specs      varchar(4000),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    version    bigint default 0 not null
);

create index idx_items_status on items (status);
create index idx_items_parent on items (parent_id);
create unique index uq_items_name_ci on items (lower(name));

create table activities (
    id           bigint generated by default as identity primary key,
    item_id      bigint not null references items (id),
    type         varchar(255) not null check (type in ('CREATED','MOVED','ASSEMBLED','CONSUMED','EDITED')),
    from_zone_id bigint references zones (id),
    to_zone_id   bigint references zones (id),
    actor        varchar(255),
    note         varchar(1000),
    occurred_at  timestamp(6) with time zone not null
);

create index idx_activities_item on activities (item_id, occurred_at desc, id desc);
