-- Aloha class production hierarchy (PostgreSQL). Replaces the placeholder item model.
--
-- WARNING: this drops and recreates items and activities. The placeholder data (grand blocks, pipe batches, tools,
-- demo history) is not carried over, because the new items are per-hull copies of the hierarchy. Do NOT run this against
-- a database whose item history you need to keep; export it first. Dropping activities removes its append-only
-- triggers from V2, so they are created again at the bottom.
--
-- The plan tables (phases, areas, hierarchy_nodes, design_basis) are filled by the application on first start from
-- seed/aloha-hierarchy.json (HierarchyLoader), not by this script.

drop table activities;
drop table items;

alter table zones add column facility varchar(255);

create table phases (
    phase_number integer primary key,
    name         varchar(255) not null,
    facility     varchar(255) not null,
    applies_to   varchar(255) not null
);

create table areas (
    id            bigint generated by default as identity primary key,
    code          varchar(2) not null unique,
    name          varchar(255) not null,
    function_desc varchar(300),
    confidence    varchar(300),
    note          varchar(600),
    sort_order    integer not null
);

create table hierarchy_nodes (
    id                bigint generated by default as identity primary key,
    node_level        varchar(255) not null check (node_level in ('UNIT','BLOCK','SECTION','PROCESS','VESSEL')),
    code              varchar(255) not null unique,
    parent_id         bigint references hierarchy_nodes (id),
    area_id           bigint references areas (id),
    long_band         varchar(255),
    latitude          varchar(255),
    side              varchar(255),
    primary_phase_id  integer not null references phases (phase_number),
    phase_route       varchar(255),
    assembly_facility varchar(255),
    erection_order    integer,
    outfit_heavy      boolean,
    function_desc     varchar(300),
    confidence        varchar(300),
    note              varchar(600),
    sort_order        integer not null
);

create index idx_node_parent on hierarchy_nodes (parent_id);

create table design_basis (
    id         bigint generated by default as identity primary key,
    item       varchar(255) not null,
    item_value varchar(500) not null,
    status     varchar(255) not null,
    source     varchar(300),
    sort_order integer not null
);

create table items (
    id         bigint generated by default as identity primary key,
    name       varchar(255) not null unique,
    hull_id    bigint not null references hulls (id),
    node_id    bigint not null references hierarchy_nodes (id),
    parent_id  bigint references items (id),
    status     varchar(255) not null check (status in ('PLANNED','ACTIVE','CONSUMED')),
    zone_id    bigint references zones (id),
    phase_id   integer not null references phases (phase_number),
    specs      varchar(4000),
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,
    version    bigint default 0 not null,
    constraint uk_item_hull_node unique (hull_id, node_id)
);

create index idx_item_status on items (status);
create index idx_item_parent on items (parent_id);
create unique index uq_items_name_ci on items (lower(name));

create table activities (
    id           bigint generated by default as identity primary key,
    item_id      bigint not null references items (id),
    type         varchar(255) not null check (type in ('CREATED','PLACED','MOVED','PHASE_CHANGED','ASSEMBLED','CONSUMED','EDITED')),
    from_zone_id bigint references zones (id),
    to_zone_id   bigint references zones (id),
    actor        varchar(255),
    note         varchar(1000),
    occurred_at  timestamp(6) with time zone not null
);

create index idx_activities_item on activities (item_id, occurred_at desc, id desc);

-- Append-only audit trail again (same function as V2, recreated triggers).
create trigger activities_no_update_delete
    before update or delete on activities
    for each row execute function reject_activity_change();

create trigger activities_no_truncate
    before truncate on activities
    for each statement execute function reject_activity_change();
