-- People who may use the app, and an audit trail of what administrators did on the Admin page.
--
-- app_users: filled by the app. A row is created the first time someone signs in (role empty: they see nothing until an
-- administrator grants one), or in advance by an administrator (username or e-mail only, until the person signs in).
-- username and email are stored lower-case. Roles set here are added to the roles from the application configuration
-- (YARD_VIEWERS / YARD_EDITORS / YARD_ADMINS), which always win and cannot be disabled here (break-glass administrators).

create table app_users (
    id            bigint generated by default as identity primary key,
    username      varchar(255) unique,
    email         varchar(320) unique,
    display_name  varchar(255),
    role          varchar(20),
    enabled       boolean not null default true,
    created_at    timestamp(6) with time zone not null,
    last_login_at timestamp(6) with time zone,
    constraint ck_app_users_role check (role is null or role in ('VIEWER','EDITOR','ADMIN')),
    constraint ck_app_users_who  check (username is not null or email is not null)
);

create table admin_events (
    id          bigint generated by default as identity primary key,
    occurred_at timestamp(6) with time zone not null,
    actor       varchar(255) not null,
    action      varchar(40) not null,
    target      varchar(255),
    detail      varchar(1000)
);

create index idx_admin_events_time on admin_events (occurred_at desc, id desc);

-- Append-only, like the item history: administrators cannot edit or erase what they did.
create or replace function reject_audit_change() returns trigger as $$
begin
    raise exception '% is append-only (% blocked)', tg_table_name, tg_op;
end;
$$ language plpgsql;

create trigger admin_events_no_update_delete
    before update or delete on admin_events
    for each row execute function reject_audit_change();

create trigger admin_events_no_truncate
    before truncate on admin_events
    for each statement execute function reject_audit_change();
